name: Lint

on:
  pull_request:
    types: [opened, synchronize]

jobs:

  lint:

    runs-on: ubuntu-latest

    matrix:
      node: [18]

    name: 'Lint'

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      - name: Build for staging server
        run: yarn lint